### ISSUE TITLE
Kafka Streams tracing

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/java-kafka-client#11]

**Comment by malafeev** [comment]
I cannot find a way to instrument kafka streams.

**Comment by nachomdo** [comment]
I think with Kafka Streams you can provide a `KafkaClientSupplier` so you can return your TrackingKafkaConsumer and TrackingKafkaProducer instead of the original one. Another option that I think could be useful to is to use `ConsumerInterceptor` and `ProducerInterceptor`, that way you can add or remove the tracing at the KafkaStreams configuration level.

**Comment by malafeev** [comment]
thank you @nachomdo 
I will try

**Comment by malafeev** [comment]
but looks like there is no way to intercept action when stream finished processing some item.
